**Data Encapsulation and Data Abstraction:**


**1. Create a class Student with attributes name (private), age (protected), and marks (public). Implement methods to set and get the values of the private and protected attributes. Create an instance of the class and demonstrate how to use these methods to access and modify the attributes.**

**2. Create a base class Shape with a protected attribute area. Implement subclasses Circle and Rectangle that calculate their respective areas. Make use of protected members to store and access the calculated areas.**

**3. Write a class Calculator that implements a method evaluate expression() to calculate the result of an arithmetic expression following the PEMDAS rule.**

**4. Create a program that reads data from a CSV file named data.csv containing student names and their scores. Implement a class Student with attributes name and score. Read the data from the CSV file and create instances of the Student class for each student. Compute the average for the class using a numpy function**



In [23]:
class Student:
    def __init__(self, age, marks, name):
        self._age = age
        self.marks = marks
        self.__name = name

    def get_name(self):
        return self.__name

    def set_name(self, name):
        self.__name = name

    def get_age(self):
        return self._age

    def set_age(self, age):
        self._age = age

class age(Student):
    def __init__(self, age, marks, name):
        Student.__init__(self, age, marks, name)
        #print("Name (private): ", self.__name)
        print("Age in class Student is: ", self._age)
        self._age = 25
        print("Modified age in subclass: ", self._age)
        print()
        print("Marks in class Student is: ", self.marks)
        self.marks = 98
        print("Modified marks in subclass: ", self.marks)

obj1 = age(20, 100, "Sugandh")  # We can modify protected variable in subclass
obj2 = Student(20, 100, "Sugandh")


print()
print("Original Name:", obj2.get_name())  # We can modify private variable only in the main class
obj2.set_name("Sugandh Mittal")
print("Updated Name:", obj2.get_name())
print()

print("Original Age:", obj2.get_age())  # We can modify age in main class as well as subclass (as shown above)
obj2.set_age(21)
print("Updated Age:", obj2.get_age())
print()

print("Original Marks:", obj2.marks)  # We can update this type of variable anywhere.
obj2.marks = 97
print("Updated Marks:", obj2.marks)



Age in class Student is:  20
Modified age in subclass:  25

Marks in class Student is:  100
Modified marks in subclass:  98

Original Name: Sugandh
Updated Name: Sugandh Mittal

Original Age: 20
Updated Age: 21

Original Marks: 100
Updated Marks: 97


In [29]:
class Shape():
  def __init__(self):
    self._area=area

class Circle(Shape):
  def __init__(self,radius):
    self.radius=radius

  def calculate_area(self):
    self._area=self.radius**2*3.14


class Rectangle(Shape):
  def __init__(self,length,width):
    self.length=length
    self.width=width

  def calculate_area(self):
    self._area=self.length*self.width

circle = Circle(8)
circle.calculate_area()
print("Area of circle:", circle._area)

rectangle = Rectangle(3, 5)
rectangle.calculate_area()
print("Area of rectangle:", rectangle._area)

Area of circle: 200.96
Area of rectangle: 15


In [28]:
class Calculator:
    def expression(self, expression):
        # Define a dictionary to hold operator precedence
        precedence = {'+': 1, '-': 1, '*': 2, '/': 2, '^': 3}

        # Define functions to perform operations
        def apply_operator(operators, values):
            operator = operators.pop()
            right = values.pop()
            left = values.pop()
            if operator == '+':
                values.append(left + right)
            elif operator == '-':
                values.append(left - right)
            elif operator == '*':
                values.append(left * right)
            elif operator == '/':
                values.append(left / right)
            elif operator == '^':
                values.append(left ** right)

        def greater_precedence(op1, op2):
            return precedence[op1] > precedence[op2]

        def evaluate(exp):
            values = []
            operators = []
            i = 0
            while i < len(exp):
                if exp[i] == ' ':
                    i += 1
                    continue
                if exp[i] in '0123456789':
                    j = i
                    while i < len(exp) and exp[i] in '0123456789.':
                        i += 1
                    values.append(float(exp[j:i]))
                elif exp[i] in '+-*/^':
                    while (operators and operators[-1] in '+-*/^' and
                           greater_precedence(operators[-1], exp[i])):
                        apply_operator(operators, values)
                    operators.append(exp[i])
                    i += 1
                elif exp[i] == '(':
                    operators.append(exp[i])
                    i += 1
                elif exp[i] == ')':
                    while operators[-1] != '(':
                        apply_operator(operators, values)
                    operators.pop()
                    i += 1
            while operators:
                apply_operator(operators, values)
            return values[0]

        return evaluate(exp)


# Example usage:
calculator = Calculator()
exp = "(2^3)+5-4"
result = calculator.expression(exp)
print("Result:", result)


Result: 9.0


In [30]:
import csv
import numpy as np

class Student():
  def __init__(self,name,score):
    self.name=name
    self.score=score

def read_data_from_csv(file_name):
    students = []
    with open(file_name, 'r') as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for row in csv_reader:
            name = row['Name']
            score = float(row['Score'])
            student = Student(name, score)
            students.append(student)
    return students

def compute_average(students):
   scores = [student.score for student in students]
   average = np.mean(scores)
   return average


if __name__ == "__main__":
    file_name = "data.csv"
    students = read_data_from_csv(file_name)

    if students:
        class_average = compute_average(students)
        print(f"Class Average Score: {class_average:.2f}")
    else:
        print("No student data found in the CSV file.")

FileNotFoundError: ignored

**Welcome To Numpy**

This assignment will help you the explore the Numpy library and its various uses. It would also cover some use cases about how numpy makes Machine Learning and Data Science calculations easy and fast. This assignment is made in order to encourage you to explore more and more builtin functions of this library and their usage. For all problems, you need to print the output.




**Importing Numpy**

The first step involves importing Numpy so that you can start using it right away. There are a lot of ways to do so depending upon how you want to use library or some functions of it. In general, we import it all together and in order to avoid writing numpy again and again, we abbreviate it in some form. For ex. np. Import the Numpy library as np in the below cell.

In [ ]:
import numpy as np

**Arrays In Numpy**

As already discussed in class, there are various ways of making numpy arrays. In the below cells we would test your ability to implement them correctly.

**Create a numpy array of 1's of user defined dimensions**

Take input for 2 dimensions : N and M, create a 2D matrix of 1's. Note : In general you can make numpy arrays of any number of dimensions. eg. 3, 4, and so on...

In [ ]:
N=int(input("Enter the number of rows: "))
M=int(input("Enter the number of columns: "))
arr=np.ones((N,M))
print(arr)

Enter the number of rows: 3
Enter the number of columns: 4
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Create an empty array Using Numpy**

When you print your array, you might see random values in your array. Repeat instructions as mentioned for previous cell.


In [ ]:
N=int(input("Enter the number of rows: "))
M=int(input("Enter the number of columns: "))
arr=np.random.rand(N,M)
print(arr)

Enter the number of rows: 3
Enter the number of columns: 4
[[0.23085356 0.95153235 0.46067737 0.43016385]
 [0.47641187 0.00654495 0.51532728 0.40070894]
 [0.47533995 0.70265414 0.69866543 0.9208977 ]]


**Create a numpy array of 0's of user defined dimensions**

Repeat instructions as mentioned previously


In [ ]:
N=int(input("Enter the number of rows: "))
M=int(input("Enter the number of columns: "))
arr=np.zeros((N,M))
print(arr)

Enter the number of rows: 3
Enter the number of columns: 4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Create a numpy array from numbers 1 to 10 using inbuilt functions**

This task can be implemented using 2 functions : **arange()** and **linspace()**. You have to make use of both of them in cells given below

In [ ]:
arr=np.linspace(1,10,10)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
arr= np.arange(1,11,1,float)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


**Convert a simple list to array**

Create a 1D list and a 2D list and convert them to numpy arrays. You need to print the type of both after conversion in order to check if they are really converted or not.

In [ ]:
lst=[]
for i in range(10):
  lst.append(i)
print(lst)

arr=np.asarray(lst)
print(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
rows, cols = (5, 5)
lst = [[i for i in range(cols)] for j in range(rows)]
print(lst)

arr=np.asarray(lst)
print(arr)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**Conversion Of Data Types in Numpy arrays**

In this problem, you need to convert float numpy array to integer type and vice versa. You need to print the array after each conversion.

In [ ]:
a = [[1,2,3],[4,5,6]]

In [ ]:
arr=np.asarray(a)
print(arr.dtype)

int64


In [ ]:
arr1=arr.astype('float64')
print(arr1)


[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
arr2=arr1.astype('int64')
print(arr2)

[[1 2 3]
 [4 5 6]]


**Given below is an array of 20 elements. Convert this array into 2D matrices of dimensions 1 x 20, 2 x 10, 4 x 5, 5 x 4, 10 x 2 and 20 x 1**

**For each given dimensions, you need to print the new array**

**For the 1 x 20 array, print every third element using indexing & slicing**

**Use the array splitter function for the 10 x 2 array having results with 3 elements**

**Concatenate arrays 10 x 2 and 20 x 1 using concatenate(), hstack(),vstack, dstack() or using axis values, you may combine reshape() for either arrays so that all the functions work, provide comments while you stack arrays for the reader to have clarity for the steps**

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(a)
print(a[::3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  4  7 10 13 16 19]


In [ ]:
a1=np.resize(a,(2,10))
print(a1)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [ ]:
a2=np.resize(a,(4,5))
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
a3=np.resize(a,(5,4))
print(a3)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
a4=np.resize(a,(10,2))
print(a4)
print(np.array_split(a4, 3))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12],
       [13, 14]]), array([[15, 16],
       [17, 18],
       [19, 20]])]


In [ ]:
a5=np.resize(a,(20,1))
print(a5)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


In [ ]:
print("reshaped a5 and concatenated along axis=0")
print(np.concatenate((a4,np.reshape(a5,(10,2)))))
print()

print("reshaped a5 and concatenated along axis=1")
print(np.concatenate((a4,np.reshape(a5,(10,2))),axis=1))
print()

print("reshaped a5 and hstack")
print(np.hstack((a4,np.reshape(a5,(10,2)))))
print()

print("reshaped a5 and vstack")
print(np.vstack((a4,np.reshape(a5,(10,2)))))
print()

print("reshaped a5 and dstack")
print(np.dstack((a4,np.reshape(a5,(10,2)))))
print()


reshaped a5 and concatenated along axis=0
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

reshaped a5 and concatenated along axis=1
[[ 1  2  1  2]
 [ 3  4  3  4]
 [ 5  6  5  6]
 [ 7  8  7  8]
 [ 9 10  9 10]
 [11 12 11 12]
 [13 14 13 14]
 [15 16 15 16]
 [17 18 17 18]
 [19 20 19 20]]

reshaped a5 and hstack
[[ 1  2  1  2]
 [ 3  4  3  4]
 [ 5  6  5  6]
 [ 7  8  7  8]
 [ 9 10  9 10]
 [11 12 11 12]
 [13 14 13 14]
 [15 16 15 16]
 [17 18 17 18]
 [19 20 19 20]]

reshaped a5 and vstack
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

reshaped a5 and dstack
[[[ 1  1]
  [ 2  2]]

 [[ 3  3]
  [ 4  4]]

 [[ 5  5]
  [ 6  6]]

 [[ 7  7]
  [ 8  8]]

 [[ 9  9]
  [10 10]]

 [[11 11]
  [12 12]]

 [[13 13]
  [14 14]]

 [[15 15]
  [16 16]]

 [[

**Find maximum element in array and print its value and its index using numpy inbuilt functions**

In [ ]:
a = np.array([100,40,30,106,4589,2,34,76,9777,1023,56,62,395])

In [ ]:
value=np.max(a)
index=np.argmax(a)
print(f"Max value: {value} and Max index: {index}")

Max value: 9777 and Max index: 8


**Print Dimensions Of The Given Array, shape of the array and size**

**Iterate through the array 'a' skipping a value and printing the next value.**

**Implement reshape on this array with your choice of parameters (not 1D)**

**Make a 1D array also and sort the array, then find the indices of values ==6 using numpy functions**

**On the 1D array, implement a numpy function to print values only above 100**



In [ ]:
a = np.array([[1,2,3],[4,5,6],[6,7,8],[7,8,9],[10,102,546]])

In [ ]:
# Printing array dimensions (axes)
print("No. of dimensions: ", a.ndim)

# Printing shape of array
print("Shape of array: ", a.shape)

# Printing size (total number of elements) of array
print("Size of array: ", a.size)


No. of dimensions:  2
Shape of array:  (5, 3)
Size of array:  15


In [ ]:
#Middle value for row will be skipped
for row in a:
    skip_next = False
    for value in row:
        if not skip_next:
            print(value)
        skip_next = not skip_next

1
3
4
6
6
8
7
9
10
546


In [ ]:
print(np.reshape(a,(3,5)))

[[  1   2   3   4   5]
 [  6   6   7   8   7]
 [  8   9  10 102 546]]


In [ ]:
b=np.reshape(a,(15))
print(b)
print(np.sort(b))
indices = np.where(b == 6)[0]
print("Indices of values equal to 6:", indices)

[  1   2   3   4   5   6   6   7   8   7   8   9  10 102 546]
[  1   2   3   4   5   6   6   7   7   8   8   9  10 102 546]
Indices of values equal to 6: [5 6]


In [ ]:
print("Array in which values are above 100: ", a[a>100])

Array in which values are above 100:  [102 546]


**Create a NumPy array with the integers from your birthdate (year, month, and day)**

**Retrieve the year.**

**Replace the year with the current year**

**Create a NumPy array containing every 3rd number from 567 to 890. What is the 8th number in this array?  What is the 15th?**

In [ ]:
birth_date = np.array([2002, 9, 20])
print("Birthdate:", birth_date)

Birthdate: [2002    9   20]


In [ ]:
Birth_Year=birth_date[0]
print(Birth_Year)

2002


In [ ]:
birth_date[0]=2023
print(birth_date)

[2023    9   20]


In [ ]:
arr=np.arange(567,890,3)
print(arr)
print()

#8th number will be on index 7 as numbering starts from 0
b=arr[7]
print("8th number: ",b)
print()

#15th number will be on index 14 as numbering starts from 0
c=arr[14]
print("15th number: ",c)

[567 570 573 576 579 582 585 588 591 594 597 600 603 606 609 612 615 618
 621 624 627 630 633 636 639 642 645 648 651 654 657 660 663 666 669 672
 675 678 681 684 687 690 693 696 699 702 705 708 711 714 717 720 723 726
 729 732 735 738 741 744 747 750 753 756 759 762 765 768 771 774 777 780
 783 786 789 792 795 798 801 804 807 810 813 816 819 822 825 828 831 834
 837 840 843 846 849 852 855 858 861 864 867 870 873 876 879 882 885 888]

8th number:  588

15th number:  609


**Evaluate (PEMDAS):**
1. ((((12+7)*2)-4)/2)-13
2. 5+5/5
3. 2*5//4
4. 2\*\*3\*\*2
5. (2\*\*3)\*\*2

In [ ]:
num_1=((((12+7)*2)-4)/2)-13
print(num_1)

4.0


In [ ]:
num_2=5+5/5
print(num_2)

6.0


In [ ]:
num_3=2*5//4
print(num_3)

2


In [ ]:
num_4=2**3**2
print(num_4)

512


In [ ]:
num_5=(2**3)**2
print(num_5)

64
